if(y<=other.bbox_top)and(yvel>0)and(other.object_index!=EnemyCorpse)
{
	if(other.object_index=Nerdy)
	{
		playsound(HitSound,.1)
		playsound(StompSound,.1)
		instance_create_depth(x,other.bbox_top,depth-1,Effect)
		yvel=-6
		animation=0
		other.image_index=0
		other.sprite_index=NerdyBounceSpr
	}
	else
	{
		playsound(HitSound,.1)
		playsound(StompSound,.1)
		instance_create_depth(other.x,other.y,depth-100,Effect,{sprite_index:KillSpr,maxframes:4.5})
		instance_create_depth(x,other.bbox_top,depth-1,Effect)
		yvel=-4
		animation=0
		other.yvel+=4
		instance_destroy(other)
	}
}